---
title: "[CATCHY TITLE]"
author:
- Hoyt Gong
- Younghu Park
- Hiyori Yoshida
output:
  pdf_document:
    toc: yes
    toc_depth: '4'
  html_document:
    code_folding: show
    highlight: haddock
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
  word_document:
    toc: yes
    toc_depth: '4'
---

#Summary 

#Description of the Problem

#Description of the Data

#Data Cleaning and Preparation

```{r}
library(plyr)    
multMerge = function(mypath){
  filenames = list.files(path = mypath, full.names = TRUE)
  datalist = lapply(filenames, 
                    function(x){read.csv(file = x,
                                         header = TRUE,
                                         stringsAsFactors = FALSE)})
  Reduce(function(x,y) {merge(x, y, all = TRUE)}, datalist)
}

my_data <- multMerge("Kickstarter_2019-11-14T03_20_27_004Z")

```

```{r}
my_data
```

#Model Overview

#Models

##Logistic Regression

##Random Forest

#Comparison of Methods 

#Final Model 

#Validity of Results and Future Improvement

#Conclusion

#Appendix

#Works Cited

#Appendix

